server:
  port: 9999

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    check-template: false
#    prefix: file:src/main/resources/templates/

  jpa:
    show-sql: true

  datasource:
    initialization-mode: always
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/myapp1?serverTimezone=Asia/Seoul
    username: root
    password: mysql

mybatis:
  type-aliases-package: com.myproject.demo.springboot.entity
  mapper-locations: mapper/**/*.xml